### ISSUE TITLE
Attachments: when adding a new attachment, file extension needs to be part of the file name

### ISSUE THREAD

**Issue by codergrl** [Esri/data-collection-ios#171] opened 2019-03-25 18:41 UTC
When adding a new attachment, the file extension needs to be part of the file name. Currently, the app allows user to rename the image they have taken, and the file extension isn't saved. This causes the file to be saved without an extension. There is metadata associated with the file that points to the mime type, but that isn't sufficient. The metadata isn't persisted when another user downloads the attachment from AGO and wants to open it on their desktop. 

Here's what the metadata looks like in .NET for the image added from the iOS app: 
![image](https://user-images.githubusercontent.com/20545379/54945282-b1969a00-4ef2-11e9-9df8-c6bdb2a9885e.png)

I also tried downloading the file to my desktop and opening it, and Windows doesn't know what to do with it.

**Comment by mikewilburn** [comment] 2019-04-01 19:24
I also confirmed on Collector for iOS that the application does not render images without a file extension on them.

When attaching images with Collector, it permits renaming the file, but auto-appends the extension independent of the filename the user specifies.

**Comment by esreli** [comment] 2019-04-01 21:44
@codergrl this issue has been fixed and merged into `v.next`. Would you please confirm?

**Comment by mikewilburn** [comment] 2019-04-01 21:58
@esreli I'll pull the latest and also confirm during my testing!

**Comment by esreli** [comment] 2019-04-01 22:01
Thanks @mikewilburn. In testing, I offer some expected inputs -> outputs:

- "image" -> "image.jpeg"
- "image.jpg" -> "image.jpg"
- "image.jpeg" -> "image.jpeg"
- "image.tiff" -> "image.tiff.jpeg"

**Comment by mikewilburn** [comment] 2019-04-01 22:19
All of those look good to me except that fourth one. In the event that a known image extension is already present, do we want to enforce appending our own?
I realize this may be non-trivial case to handle the logic for, so not encouraging the behavior, just posing the question.

**Comment by esreli** [comment] 2019-04-01 22:33
> do we want to enforce appending our own?

Yes. The app will generate a `jpeg` data file. If someone tries to give that `jpeg` file a `tiff` file extension, it needs to override `.tiff` otherwise the file cannot be opened.

**Comment by mikewilburn** [comment] 2019-04-02 16:28
I've confirmed on the `v.next` branch that the `.jpeg` extension is now being appended to the name of all image attachments uploaded by the app.
With the extension present, this ensures the app can always recognize the file type and render it appropriately during subsequent viewing.

In my testing, `.jpg` and `.jpeg` are the only extensions present on the original, user-specified filename that _will not_ result in an additional `.jpeg` extension being appended.

**Comment by esreli** [comment] 2019-04-02 17:21
That's correct, this is the rule i've implemented:

```swift
if fileExtension != "jpeg" && fileExtension != "jpg" {
     jpegName.append(".jpeg")
}
```

Is this issue good to close?

**Comment by mikewilburn** [comment] 2019-04-02 17:51
@esreli Yes, I think so. Though we might also give @codergrl time to evaluate and comment since she's the one who opened the issue.

**Comment by codergrl** [comment] 2019-04-04 18:11
> The app will generate and upload a jpeg data file, no matter what the original file type.

I don't feel this is a good idea. It doesn't make for a generic app if we're forcing everything to be jpg. The app should only add an extension if the extension doesn't already exist. If it exists, leave it as is.

**Comment by esreli** [comment] 2019-04-04 18:17
> I don't feel this is a good idea.

I'm implementing this solution using this [popup attachment manager API](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_popup_attachment_manager.html#a9606cea7ec9b1a1d20cd5da1e52e15a4).

Using a different API to accomplish this task is fine but will require a change in approach.

**Comment by codergrl** [comment] 2019-04-04 18:25
I fail to see how this would require a different approach outside of the API.

```if fileExtension == ""
    fileName.apped(".jpeg")```

**Comment by esreli** [comment] 2019-04-04 18:26
If the image file selected is not a `.jpeg`, the SDK will convert it to one.

**Comment by codergrl** [comment] 2019-04-04 18:31
Then maybe the `addAttachmentAsJPGWithImage` isn't the right method to use in this case since it's so limiting

**Comment by esreli** [comment] 2019-04-04 18:31
Let me elaborate. I will have to use a different API than the one i've selected from the popup attachment manager. I would probably use [this one](https://developers.arcgis.com/ios/latest/api-reference/interface_a_g_s_popup_attachment_manager.html#a23bfef7aaa1e99770ccc6c9566cb4ade) which requires a different approach to managing the staged photo attachment model as well as introduces an async completion, changing the workflow I have in place for actually persisting. This is fine, but it's more than a few lines of code.

**Comment by esreli** [comment] 2019-04-04 18:34
I will suggest that iOS is a platform that de-emphasizes files themselves in favor of simply accomplishing a task. In this case, the task we are trying to accomplish is to upload an image. The SDK will simply accomplish this task, no matter how it gets there.

**Comment by jf990** [comment] 2019-04-04 19:15
We should review this functionality and consult some others as far as its purpose in order to know the correct implementation. On the surface, this seems wrong to me.

If a field collection app is collecting raster files, uploading a file of type .tiff would potentially be a raster image. converting it to jpeg as jpeg is a lossy image compression would render the .tiff useless. in a scenario like this changing the file type from the users intention would be incorrect behavior.

If the app is just uploading images for the purpose of image display to human eyes, then maybe this is ok. what if the file was not an image (a PDF) ? or a PNG (png offers transparency while jpeg does not, so converting png to jpeg loses that information)

i've never been in favor of doing something the user did not ask for. if we are going to change the name or the data type of the file, we should be clear about it and offer the user the option to preserve the original.

**Comment by esreli** [comment] 2019-04-04 20:09
Sure, i'll modify the implementation. I reasoned this solution was fine on the basis of:

- Functional specs only specified support for static images. 
- The workflow will only ever allow static images processed by the attachments manager in this manager
- iOS isn't built on a traditional files/docs directory usage pattern
- This was the most simple implementation supported by our SDK

It's fine with me to scrap this behavior in favor of a bit more robust solution.

**Comment by jf990** [comment] 2019-04-04 20:42
> * Functional specs only specified support for static images.

if that is the intended behavior and this is an iOS only issue then maybe this is fine as-is. It may be that we seek a more robust solution on the other platforms. That's why I thought it worthy of a broader discussion.

**Comment by esreli** [comment] 2019-04-05 20:06
This change has been implemented. Please confirm.

**Comment by mikewilburn** [comment] 2019-04-12 00:48
Confirmed that these latest changes now permit alternative image types to be selected and these are now persisted in the app.

File types tested:
- [x] .png
- [x] .jpg
- [x] .gif
- [x] .bmp --> not renderable on iOS, but gets persisted to feature & can be successfully rendered in web browser
- [ ] .tiff --> still need to do some additional testing (is getting attached as a `.bin` file and not being persisted after the edits are saved)

**Comment by esreli** [comment] 2021-02-01 20:07
This issue has long been resolved, closing issue.

**Closed by esreli** 2021-02-01 20:07 UTC
Labels: Priority - High, Type - Bug
